# Generated by Django 4.0.1 on 2022-01-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='creditos',
            field=models.IntegerField(null=True),
        ),
    ]
