# Generated by Django 4.0.1 on 2022-01-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_cursos_costo_alter_cursos_creditos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
