# Generated by Django 4.0.1 on 2022-01-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_cursos_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
